### PR TITLE
Fixing the COVID-19 tag, putting it at the top of diseases list

### LINKED ISSUE #96: COVID-19 tag at the beginning of the tag list
To better highlight COVID-19 content, it would be helpful to put SARS-CoV2 tag at the beginning of the tag list on the left and maybe bold it or highlight it somehow.

### PR DESCRIPTION
**Pull request by harumhelmy**
Fixes #96.

This is a product of pairing with @rudietuesdays!

For now, we hard coded COVID-19 into the top of the DISEASES constant that populates the disease subject tag list. We added some styling to highlight it. 

For a future feature, we would want to add a "featured" flag or something to diseases so that putting them at the top of the list can be done programatically. 

Screen Shot 2020-05-15 at 16 28 33

Screen Shot 2020-05-15 at 16 29 02

### CODE REVIEW

File: src/constants.js [hunk 1]
```diff
@@ -203,7 +203,7 @@ export const DISEASES = [
 
   {
     name: '2019 novel coronavirus',
```
Comment (harumhelmy) [inline src/constants.js]: I think this is also technically incorrect, as "2019 novel coronavirus" is the name of the pathogen, not the disease. Let me know if you'd like this fixed as well, @georgiamoon!

Comment (georgiamoon) [reply src/constants.js]: Yes! The team made a mistake earlier this year when they named it that. Thanks!

File: src/constants.js [hunk 2]
```diff
@@ -137,6 +137,12 @@ export const INDEXED_PREPRINT_PROPS = [
 
 // See https://github.com/PREreview/rapid-prereview/issues/10
 export const DISEASES = [
+  {
+    name: '2019 novel coronavirus',
```
Comment (georgiamoon) [inline src/constants.js:141]: @majohansson Should we have the name '2019 novel coronavirus' at all?

Comment (georgiamoon) [reply src/constants.js:141]: This won't display in the interface, but I'm wondering if it should just be 'COVID-19' fullstop.

**Comment by georgiamoon** [comment]
As far as my ability to read the code, this all LGTM. I pinged @majohansson on the name/alt name for COVID-19, but from my perspective this is good to merge.

File: src/constants.js (hunk 1 above)
Comment (harumhelmy) [reply src/constants.js]: Okie, just changed it to "Coronavirus disease 2019" for the disease name.
